### ISSUE TITLE
Data Folder Empty？

### ISSUE THREAD

**Issue by JesusLoveKennyp** [Y-Claw/Multilevel-GNN#1]
There seems to be something wrong with the link to get the data, the Multilevel GNN Data folder is empty.

**Comment by Y-Claw** [comment]
There seems to be some problems with google driver and the data file has been re-uploaded.

**Comment by JesusLoveKennyp** [comment]
Got it working, thank you very much. 
I will close the issue then. Inspiring work by the way!
